### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by Gamerboi10272003** [Fetty42/FS22_SiloFilltypeLimiting#3]
My game crashed when i turned on an auger over one of the in game grain bins. i noticed it did not crash when there is something in the auger and only crashed if the auger was on and empty. probly not a big issue just a little inconvenient.

[log.txt](https://github.com/Fetty42/FS22_SiloFilltypeLimiting/files/11176232/log.txt)

**Comment by Fetty42** [comment]
Sorry, I'm not able to reproduce your problem and the code line looks ok.
Do you have the same problem with other maps and without all the other user mods?

If you want, you could also make the following change in the file SiloFilltypeLimiting.lua, so that some more info is written into the LOG

line 5:
local dbPrintfOn = false
to
local dbPrintfOn = true

**Comment by Gamerboi10272003** [comment]
i was able to recreate it on a separate world with only this mod and the Agi pack. i used the Agi Westeel hopper bin that holds 125,000l and the STX 10-51 Auger. i noticed it would only crash if i had automatic engine start turned off.
(i'm using the Agi pack because that's what i had a problem with i thought they were base game before)

[log.txt](https://github.com/Fetty42/FS22_SiloFilltypeLimiting/files/11180188/log.txt)

**Comment by Fetty42** [comment]
Many thanks for the information. I have now been able to reproduce the error and correct it.
